version: '3'

services:

  db:
    #image: postgres
    build: ./postgres
    restart: unless-stopped
    expose:
      - "5432"
    environment:   # will be used by the init script
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data/  # persist container's db data to local pgdata/ (mounted)

  web:
    build: ./djangoweb
    # command: python3 manage.py runserver 0.0.0.0:8000
    command: gunicorn djangoweb.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8087:80"  # host:container 
    #links:
    #  - web
    depends_on:
      - web
